[package]
name = "zkwork-pool-protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde = "1.0.138"
serde_json = "1.0.82"
erased-serde = "0.3.21"


[dependencies.snarkos]
git = "ssh://git@github.com/ABMatrix/snarkOS.git"
branch = "testnet3"

[dependencies.snarkvm]
git = "ssh://git@github.com/ABMatrix/snarkVM.git"
branch = "testnet2"
